# Camera Configuration for Jetson Nano

# Camera settings
camera:
  # Camera type: 'usb', 'csi', or 'ip'
  type: 'usb'
  
  # Camera device ID (for USB cameras)
  device_id: 0
  
  # CSI camera settings (if using CSI camera)
  csi:
    sensor_id: 0
    sensor_mode: 0
    flip_method: 0
    
  # IP camera settings (if using network camera)
  ip:
    url: "rtsp://192.168.1.100:554/stream"
    username: ""
    password: ""

# Video capture settings
capture:
  width: 1280
  height: 720
  fps: 30
  buffer_size: 1  # Reduce latency
  
# Image preprocessing
preprocessing:
  resize_width: 640
  resize_height: 640
  normalize: true
  mean: [0.485, 0.456, 0.406]  # ImageNet means
  std: [0.229, 0.224, 0.225]   # ImageNet stds

# Display settings
display:
  show_preview: true
  preview_width: 640
  preview_height: 480
  show_fps: true
  show_detections: true
  
# Recording settings
recording:
  enabled: false
  output_dir: "recordings"
  format: "mp4"
  codec: "mp4v"

# Performance settings
performance:
  threading: true
  queue_size: 2
  timeout: 5.0  # seconds
