# Model Information and Metadata
# 模型信息和元数据

models:
  yolov8n_character:
    name: "YOLOv8 Nano Character Detector"
    description: "Lightweight character detection model optimized for Jetson Nano"
    description_cn: "为Jetson Nano优化的轻量级字符检测模型"
    version: "1.0.0"
    file_path: "pretrained/yolov8n_character.pt"
    architecture: "YOLOv8n"
    input_size: [640, 640]
    num_classes: 36
    classes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
              'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
              'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
              'U', 'V', 'W', 'X', 'Y', 'Z']
    model_size_mb: 6.2
    parameters: 3157200
    training:
      dataset: "Synthetic Character Dataset"
      epochs: 100
      batch_size: 16
      learning_rate: 0.001
      training_time_hours: 4.5
      final_accuracy: 94.2
    performance:
      jetson_nano:
        fps: 15
        inference_time_ms: 67
        memory_usage_mb: 1200
        power_consumption_w: 8.5
      jetson_xavier:
        fps: 45
        inference_time_ms: 22
        memory_usage_mb: 1800
        power_consumption_w: 15.2
    optimization:
      tensorrt_compatible: true
      onnx_compatible: true
      quantization_supported: true
    created_date: "2024-01-15"
    last_updated: "2024-01-20"

  yolov8s_character:
    name: "YOLOv8 Small Character Detector"
    description: "Higher accuracy character detection model"
    description_cn: "高精度字符检测模型"
    version: "1.0.0"
    file_path: "pretrained/yolov8s_character.pt"
    architecture: "YOLOv8s"
    input_size: [640, 640]
    num_classes: 36
    classes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
              'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
              'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
              'U', 'V', 'W', 'X', 'Y', 'Z']
    model_size_mb: 22.5
    parameters: 11166560
    training:
      dataset: "Synthetic + Real Character Dataset"
      epochs: 150
      batch_size: 8
      learning_rate: 0.001
      training_time_hours: 12.3
      final_accuracy: 96.8
    performance:
      jetson_nano:
        fps: 8
        inference_time_ms: 125
        memory_usage_mb: 1800
        power_consumption_w: 10.2
      jetson_xavier:
        fps: 25
        inference_time_ms: 40
        memory_usage_mb: 2400
        power_consumption_w: 18.5
    optimization:
      tensorrt_compatible: true
      onnx_compatible: true
      quantization_supported: true
    created_date: "2024-01-18"
    last_updated: "2024-01-22"

  synthetic_trained:
    name: "Synthetic Dataset Trained Model"
    description: "Model trained exclusively on synthetic character data"
    description_cn: "专门在合成字符数据上训练的模型"
    version: "1.0.0"
    file_path: "custom/synthetic_trained.pt"
    architecture: "YOLOv8n"
    input_size: [640, 640]
    num_classes: 36
    model_size_mb: 6.1
    training:
      dataset: "Synthetic Character Dataset (100k images)"
      epochs: 80
      batch_size: 16
      learning_rate: 0.001
      training_time_hours: 3.2
      final_accuracy: 92.5
    performance:
      jetson_nano:
        fps: 16
        inference_time_ms: 62
        memory_usage_mb: 1150
    created_date: "2024-01-25"

# Model Download Information
# 模型下载信息
download_info:
  base_url: "https://github.com/example/jetson-character-recognition/releases/download"
  models:
    yolov8n_character:
      url: "v1.0.0/yolov8n_character.pt"
      checksum_md5: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
      size_bytes: 6502400
    yolov8s_character:
      url: "v1.0.0/yolov8s_character.pt"
      checksum_md5: "b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7"
      size_bytes: 23592960

# Model Compatibility
# 模型兼容性
compatibility:
  jetpack_versions: ["4.6", "5.0", "5.1"]
  python_versions: ["3.6", "3.7", "3.8", "3.9"]
  pytorch_versions: ["1.9.0", "1.10.0", "1.11.0", "1.12.0"]
  ultralytics_versions: ["8.0.0", "8.0.1", "8.0.2"]

# Performance Benchmarks
# 性能基准
benchmarks:
  test_dataset: "Real World Character Test Set (1000 images)"
  metrics:
    precision: 0.942
    recall: 0.938
    f1_score: 0.940
    map50: 0.945
    map50_95: 0.672
  speed_tests:
    jetson_nano_4gb:
      model_loading_time_s: 2.3
      first_inference_time_ms: 150
      average_inference_time_ms: 67
      throughput_fps: 15
    jetson_xavier_nx:
      model_loading_time_s: 1.8
      first_inference_time_ms: 80
      average_inference_time_ms: 22
      throughput_fps: 45

# Model Usage Guidelines
# 模型使用指南
usage_guidelines:
  recommended_models:
    jetson_nano: "yolov8n_character"
    jetson_xavier: "yolov8s_character"
    development: "synthetic_trained"
  optimization_tips:
    - "Use TensorRT for maximum speed on Jetson devices"
    - "Enable FP16 precision for memory efficiency"
    - "Reduce input resolution for faster inference"
    - "Use batch size of 1 for real-time applications"
  memory_requirements:
    minimum_ram_gb: 2
    recommended_ram_gb: 4
    gpu_memory_mb: 512
